import "./globals.css";

import {Inter as FontSans} from "next/font/google"

import {cn} from "@/lib/utils"
import {Toaster} from "sonner";


const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body
            className={cn(
                "h-[95vh] newBackground font-sans antialiased",
                fontSans.variable
            )}
        >

        <main>
            {children}
        </main>
        <Toaster/>
        </body>
        </html>
    );
}
